services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgres/data

  redis:
    image: eqalpha/keydb
    ports:
      - 6379:6379
    volumes:
      # - ./redis.conf:/etc/keydb/redis.conf
      - keydb_data:/data

  jaeger_opentelemetry:
    image: jaegertracing/all-in-one:1.62.0
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

volumes:
  pg_data:
    driver: local
  keydb_data:
    driver: local
